---

name: "tagged-release-with-pr-creation"

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -V

      - name: Install Tox and any other packages
        run: pip install tox

      # - name: Run Tox
      #   run: tox

  release:
    needs: [test]
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - run: python -V

      - name: setup.py sdist
        run: python setup.py sdist

      - name: release to github
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*.zip
            dist/*.gz
      - name: Upload python package
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  pr:
    needs: [release]
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'ikeikeikeike/action-test'
      - name: Download python package
        uses: actions/download-artifact@v2
        with:
          name: dist

      - run: ls -alt

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      # - name: Make changes to pull request
      #   run: date +%s > report.txt

      # - name: Create commits
      #   run: |
      #     git config user.name 'Peter Evans'
      #     git config user.email 'peter-evans@users.noreply.github.com'
      #     date +%s > report.txt
      #     git commit -am "Modify tracked file during workflow"
      #     date +%s > new-report.txt
      #     git add -A
      #     git commit -m "Add untracked file during workflow"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          delete-branch: true
          base: ${{ github.head_ref }}
          # branch: add-mypackage
          author: "${{ github.actor }} <${{ github.event.pusher.email }}>"
          committer: "${{ github.actor }} <${{ github.event.pusher.email }}>"
          commit-message: Add mypackage
          title: 'Add mypackage'
          body: |
            https://github.com/ikeikeikeike/action-test/releases
          # labels: |
          #   report
          #   automated pr
          assignees: "${{ github.actor }}"
          reviewers: "${{ github.actor }}"
          # team-reviewers: |
          #   owners
          #   maintainers
          # milestone: 1
          # draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
