---

name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Python ${{ matrix.python-version }} sample
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -V
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox

  release:
    needs: [build]
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python -V
      - name: Build & test 2
        run: |
          echo "done!"

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            *.py
