---

name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.7', '3.8' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python my_script.py

  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Build & test
        run: |
          echo "done!"

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            *.py
