---

name: "upload wiki when built doc is merged"

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  docs:
    name: Upload Documentation
    if: github.event.pull_request.merged == true && github.head_ref == 'build-documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - run: python -V

      - name: Generate Documentation as Markdown
        run: |
          pip install pdoc3
          pdoc3 myaction -f -o wiki

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki/myaction"   # TODO: cannot find subfilder: this behavior like maxdepth=1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
